language: python

python:
  - 3.6

services:
  - redis
  - mysql
env:
  - DJANGO_VERSION=2.2.13

before_install:
    - sudo mysql -e 'CREATE DATABASE dailyfresh;'
    - python -m pip install -U pip

install:
    - pip install -r requirements.txt

script: True
